app/models.py
class Source:

    ''' sources class '''

    def __init__(self, id , name, description, url, category, language, country):
        self.id = id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.language = language
        self.country = country

class Article:

    ''' articles class '''

    def __init__(self, source, author, title, description, url, urlToImage, publishedAt, content) -> None:
        self.source = source
        self.author = author
        self.title = title
        self.description = description
        self.url = url  
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options

bootstrap=Bootstrap()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .request import configure_request
    configure_request(app)


    return app

app/main/__init__.py
from flask  import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for
from .views import *
from . import main
from ..request import *

@main.route('/')
def root():
    return redirect(url_for('main.sources'))

@main.route('/sources')
def sources():
    title='sources'
    business_sources=get_sources('business')
    entertainment_sources=get_sources('entertainment')
    general_sources=get_sources('general')
    health_sources=get_sources('health')
    science_sources=get_sources('science')
    sports_sources=get_sources('sports')
    tech_sources=get_sources('technology')

    return render_template('index.html', title=title, business=business_sources,
                           entertainment=entertainment_sources, general=general_sources, health=health_sources,
                           science=science_sources, sports=sports_sources, tech=tech_sources)


@main.route('/articles/<source>')
def articles(source):
    articles = get_articles(source)
    return render_template('articles.html', title=source,articles=articles)

app/templates/articles.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <div class="container-fluid" id="container">
        <a class="navbar-brand">
          <h1>News App</h1>
        </a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="/">Home</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-6">
          {% for each in articles %}
          <span class="text-center"><b>{{each['author']}}</b></span>
          
          
        </div>
        <div class="col-6">
          <img class="img-thumbnail" src="{{ each['urlToImage']}}" alt="" />
          
          <span>{{each['description'] }}</span>
          <span><b>Published on:{{each['publishedAt'] }}</b></span>
          <a href="{{each['url']}}">Read more</a>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- navbar block -->
{% block navbar %} 
{% include 'navbar.html' %} 
{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block content%}
<div class="container">
  <h1>We can't find that page</h1>
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <div class="container-fluid" id="container">
        <a class="navbar-brand">
          <h1>News App</h1>
        </a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="/">Home</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Business</h2>
        </div>
        <div class="card-body">
          {% for source in business %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>
          {% endfor%}
        </div>
      </div>
      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Entertainment</h2>
        </div>
        <div class="card-body">
          {% for source in entertainment %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>
          {% endfor%}
        </div>
      </div>

      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Health</h2>
        </div>
        <div class="card-body">
          {% for source in health %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>
          {% endfor%}
        </div>
      </div>

      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Science</h2>
        </div>
        <div class="card-body">
          {% for source in science %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>
          {% endfor%}
        </div>
      </div>

      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Sports</h2>
        </div>
        <div class="card-body">
          {% for source in sports %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>

          {% endfor%}
        </div>
      </div>

      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-title">
          <h2>Technology</h2>
        </div>
        <div class="card-body">
          {% for source in tech %}
          <ul>
            <li>{{ source['name'] }}</li>
            <span
              ><a href="{{ url_for('main.articles', source=source['name']) }}">
                {{source.id}}</a
              ></span
            >
          </ul>

          {% endfor%}
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid" id="container">
      <a class="navbar-brand">
        <h1>NewsApp</h1>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active">home</a>
        </div>
      </div>
    </div>
  </nav>